# Generated by Django 4.2 on 2024-02-29 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_quiz_code_quiz_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opinionquestion',
            name='user',
        ),
        migrations.AddField(
            model_name='opinionquestion',
            name='answers',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
